services:
  postgres:
    image: postgres:latest
    container_name: postgres_file
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bd_lab7
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
